"""

Even Fibonacci Numbers
----------------------
Problem 2

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.


Approach
--------
Let:
	a = 1
	b = 2
	limit = 4000000

Steps:
1.)	Keep two Fibonacci terms on hand.
2.)	While the second term is less than the limit:
	a.)	Add it to the sum if it's even.
	b.)	Iterate to the next term in the sequence.

"""

a	= 1
b	= 2
limit	= 4000000


def fibonacci_sum (limit):
	summation = 0
	
	while b < limit:
		if b % 2 == 0:
			summation += b
		
		temp = a
		a = b
		b += temp
	
	return summation


print fibonacci_sum(limit)
